name: Build, Test, Package and Push

# Controls when the action will run. 
on: 
  # Triggers the workflow on pull request events and merges/pushes to main
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Configure GitHub package source ğŸ™
        id: package-source
        shell: bash
        run: dotnet nuget update source GitHub --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          
      - name: Nuke Build ğŸ—
        id: build
        shell: bash
        run: ./build.sh --verbosity verbose

      - name: Push package to GitHub ğŸ™
        id: push-github
        if: startsWith(github.ref, 'dependabot') == false
        shell: bash
        run: dotnet nuget push artifacts/**/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "GitHub" --skip-duplicate

      - name: Push package to Feedz.io ğŸ™
        id: push-feedz
        if: startsWith(github.ref, 'dependabot') == false
        shell: bash
        env:
          FEEDZ_API_KEY: ${{ secrets.FEEDZ_API_KEY }}
          FEEDZ_SOURCE: https://f.feedz.io/octopus-deploy/dependencies/nuget/index.json
        run: dotnet nuget push artifacts/**/*.nupkg --api-key "$FEEDZ_API_KEY" --source "$FEEDZ_SOURCE"
